import { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Box } from "@chakra-ui/react";
import { ColorModeButton, ColorModeProvider } from "@/components/ui/color-mode";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tuto",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <ColorModeProvider forcedTheme="light">
            <header
              style={{
                display: "flex",
                justifyContent: "space-between",
                backgroundColor: "lightblue",
                padding: "1rem",
                color: "black",
              }}
            >
              <Box>Header</Box>
              <ColorModeButton />
            </header>
            {children}
            <footer
              style={{
                backgroundColor: "ghostwhite",
                padding: "1rem",
                color: "black",
              }}
            >
              <Box>Footer</Box>
            </footer>
          </ColorModeProvider>
        </Provider>
      </body>
    </html>
  );
}
